version: '3.3'

services:

  web-farm-load-balancer:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 80:80
    depends_on:
      - web-farm-api

  web-farm-api:
    image: web-farm-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - web-farm-cache

  web-farm-cache:
    image: redis
    ports:
      - 6379:6379
